### ISSUE TITLE
Citation version

### ISSUE THREAD

**Issue by matteosantama** [radar-research-lab/MFGLib#18]
@AnranHu I notice you put the version into the citation in `README.md`. Is that standard? It means we have to remember to update it every time we bump the version (I've already bumped from v0.1.0 to v0.1.1 to fix some metadata on PyPI).

**Comment by matteosantama** [comment]
Oh sorry, for some reason I thought you added that. But looking through the commit history, I see its been there for a long time.

If no one objects, it might be easier to remove the version info from the citation.

**Comment by junziz** [comment]
I just checked a few examples. Seems that in most cases, either version is included in the citation or they only list the paper. We can change it to the paper reference once it’s uploaded to arXiv. For now, maybe just change it to 0.1.1? I think the main point of keeping the version is in case there are significant algorithm/modeling changes, etc. from old to new versions. But also okay to remove it.

**Comment by matteosantama** [comment]
Ok, version was bumped in `README.md`

**Comment by junziz** [comment]
Btw, version in documentation citation page is also outdated (0.1.0). Maybe we do need to directly get/read that version from a unified place and generate it to the README and doc. But for now let’s just manually fix it. Thanks! @matteosantama
