### ISSUE TITLE
CI Optimizations

### ISSUE THREAD

**Issue by matteosantama** [radar-research-lab/MFGLib#4]
Tracking issue for potential CI optimizations.

1. Only run testing/linting when Python code is changed, ie. ignore changes to the `docs` folder.

**Comment by AnranHu** [comment]
We should probably also ignore changes to something like README.md. Currently it seems to run CI for README changes as well. Thanks!

**Comment by mahantajrobehkar** [comment]
>  The workflows CI fail from time to time for optuna tuning test on rps. Let's catch this error as test pass as this is not a real error.

@AnranHu What is the error message you get upon failure?

**Comment by AnranHu** [comment]
> > The workflows CI fail from time to time for optuna tuning test on rps. Let's catch this error as test pass as this is not a real error.
> 
> @AnranHu What is the error message you get upon failure?

Oh you can check here for the errors: https://github.com/radar-research-lab/MFGLib/actions.

**Comment by matteosantama** [comment]
@AnranHu I believe the errors were a result of `timeout=10`. The test was timing out before being able to run the whole 5 trials. I've raised the timeout in my latest PR. 

I believe this is better than catching and ignoring the warning, because if we were to catch and ignore the warning we would have no way to tell if we mistakenly introduced a bug that prevents `tune()` from converging.

I will close this issue, but if raising the timeout proves to be inadequate we can re-open it.
